export const ROOM_ACTIONS = {
    SELECT_ROOM: 'SELECT_ROOM',
    REQUEST_ROOMS: 'REQUEST_ROOMS',
    RECEIVE_ROOMS: 'RECEIVE_ROOMS',
    INVALIDATE_ROOM_LIST: 'INVALIDATE_ROOM_LIST'
}
export const USER_ACTIONS = {
    SELECT_USER: 'SELECT_USER',
    REQUEST_USERS: 'REQUEST_USERS',
    RECEIVE_USERS: 'RECEIVE_USERS',
    INVALIDATE_USER_LIST: 'INVALIDATE_USER_LIST'
}
export const MESSAGE_ACTIONS = {
    REQUEST_MESSAGES: 'REQUEST_MESSAGES',
    RECEIVE_MESSAGES: 'RECEIVE_MESSAGES',
    INVALIDATE_MESSAGE_LIST: 'INVALIDATE_MESSAGE_LIST',
    VIEW_NEW_MESSAGE: 'VIEW_NEW_MESSAGE'
}

export const WEBSOCKET_ACTIONS = {
    CONNECT_WEBSOCKETS: 'CONNECT_WEBSOCKETS',
    SEND_MESSAGE: 'SEND_MESSAGE',
    SEND_MESSAGE_UI: 'SEND_MESSAGE_UI',
    RECEIVE_JOIN_ROOMS_MESSAGE: 'RECEIVE_JOIN_ROOMS_MESSAGE',
    RECEIVE_SOCKET_INIT_MESSAGE: 'RECEIVE_JOIN_ROOMS_MESSAGE',
    RECEIVE_CHAT_MESSAGE: 'RECEIVE_CHAT_MESSAGE',
    RECEIVE_REQUEST_USERS_ONLINE_MESSAGE: 'RECEIVE_JOIN_ROOMS_MESSAGE'
}

export const ASYNC_STORAGE_ACTIONS = {
    RECEIVE_GET_VALUE: 'RECEIVE_GET_VALUE',
    REQUEST_GET_VALUE: 'REQUEST_GET_VALUE',
    RECEIVE_SET_VALUE: 'RECEIVE_SET_VALUE',
    REQUEST_SET_VALUE: 'REQUEST_SET_VALUE'
}
export const LOGIN = 'LOGIN';




