export const ASYNC_STORAGE_VALUES = {
    AUTH_TOKEN: 'X-AUTH-TOKEN',
    CONNECTION_TOKEN: 'connectionToken'
}

export const MESSAGE_TYPES = {
    FILE_TYPE: 'file',
    TEXT_TYPE: 'text',
    DELETED_TYPE: 'deleted'
}

export const WEBSOCKET_EVENTS = {
    SOCKET_INIT_MSG: 'SOCKET_INIT_MSG',
    REQUEST_USERS_ONLINE: 'REQUEST_USERS_ONLINE',
    USER_MESSAGE: 'USER_MESSAGE',
    JOIN_ROOMS: 'JOIN_ROOMS'
}