/**
 * Created by ekaterina.dobrilko on 9/22/2016.
 */
export const SOCKET_INIT_MSG = 'SOCKET_INIT_MSG';
export const USER_ONLINE = 'USER_ONLINE';
export const USER_OFFLINE = 'USER_OFFLINE';
export const REQUEST_USERS_ONLINE = 'REQUEST_USERS_ONLINE';
export const WEB_RTC_COMMUNICATION = 'WEB_RTC_COMMUNICATION';
export const DELETE_USER_FROM_ROOM = 'DELETE_USER_FROM_ROOM';
export const BAN_USER = 'BAN_USER';
export const VIDEO_CALL_MESSAGE = 'VIDEO_CALL_MESSAGE';
export const USER_MESSAGE = 'USER_MESSAGE';
export const VIDEO_CALL_INCOME = 'VIDEO_CALL_INCOME';
export const ADD_USER_TO_ROOM = 'ADD_USER_TO_ROOM';
export const JOIN_ROOMS = 'JOIN_ROOMS';
export const NOTIFICATION = 'NOTIFICATION';
export const USER_START_TYPING_MESSAGE = 'USER_START_TYPING_MESSAGE';
export const USER_STOP_TYPING_MESSAGE = 'USER_STOP_TYPING_MESSAGE';